"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");

const context = vm.createContext({
  console,
  Assets: { T: {} },
});
vm.runInContext(fs.readFileSync("js/plugins.js", "utf8"), context, { filename: "js/plugins.js" });
vm.runInContext(fs.readFileSync("js/data.js", "utf8"), context, { filename: "js/data.js" });

function evaluate(source) {
  return vm.runInContext(source, context);
}

function migrate(project) {
  context.__input = project;
  const result = evaluate("RA.migrateProject(__input)");
  delete context.__input;
  return result;
}

// Objects produced inside the vm sandbox have that realm's Array/Object
// prototypes, so comparing them directly against main-realm objects with
// assert.deepEqual (which is deepStrictEqual under node:assert/strict) fails
// on prototype identity even when every value matches. Round-tripping through
// JSON strips realm identity -- and also matches how projects are actually
// persisted/loaded (as JSON) -- so it's the right normalization for equality
// checks here.
function plain(o) { return JSON.parse(JSON.stringify(o)); }

const latest = evaluate("RA.FORMAT_VERSION");
assert.equal(typeof latest, "number");
assert.ok(latest >= 1);

// (a) migrating a copy of the bundled sample project stamps the latest
// formatVersion and is idempotent: migrating the already-migrated project
// again produces a deep-equal result.
const sample = JSON.parse(fs.readFileSync("Atlas_Quest.json", "utf8"));
// Since the Phase 7 Stage D HD rebuild, the bundled sample is regenerated by
// scripts/build-atlas-quest-hd.mjs from a migrated document, so it ships
// already stamped at the latest version (it used to predate the field).
assert.equal(sample.meta.formatVersion, latest);

const onceMigrated = migrate(JSON.parse(JSON.stringify(sample)));
assert.equal(onceMigrated.meta.formatVersion, latest);

const twiceMigrated = migrate(JSON.parse(JSON.stringify(onceMigrated)));
assert.deepEqual(plain(twiceMigrated), plain(onceMigrated));

// (b) a project with no formatVersion (implicit version 0) runs the 0->1 step
// -- verified here via one of that step's concrete effects (states seeded,
// engine rebranded) in addition to the version stamp itself.
const legacyNoVersion = migrate({
  meta: { engine: "driftwood", version: 2 },
  plugins: [],
  assets: {},
  system: {},
  states: [],
  skills: [],
  classes: [],
  maps: [],
});
assert.equal(legacyNoVersion.meta.formatVersion, latest);
assert.equal(legacyNoVersion.meta.engine, "rpgatlas"); // a 0->1 side effect actually ran
assert.ok(Array.isArray(legacyNoVersion.system.types.elements) && legacyNoVersion.system.types.elements.length > 0); // another 0->1 side effect
assert.ok(Array.isArray(legacyNoVersion.states)); // 0->1 leaves an explicit [] as-is (not falsy)

// (c) a project already at the latest formatVersion is left untouched
// (deep-equal before/after).
const atLatest = migrate(JSON.parse(JSON.stringify(onceMigrated)));
assert.deepEqual(plain(atLatest), plain(onceMigrated));

// (d) a project with formatVersion GREATER than latest is left unmigrated.
// Forward-compat guard (see the comment above RA.FORMAT_VERSION in
// js/data.js): if a project's stamped formatVersion is already ahead of what
// this build knows about, migrateProject() runs NO steps at all and does NOT
// touch the stamped formatVersion (in particular it never downgrades it back
// to RA.FORMAT_VERSION). The project is returned exactly as given, so an
// older build won't silently mangle a newer save format it doesn't
// understand.
const fromTheFuture = {
  meta: { engine: "rpgatlas", version: 3, builtinsSeeded: true, formatVersion: latest + 5 },
  plugins: [],
  assets: {},
  system: {},
  states: [],
  skills: [],
  classes: [],
  maps: [],
};
const fromTheFutureCopy = JSON.parse(JSON.stringify(fromTheFuture));
const futureResult = migrate(fromTheFutureCopy);
assert.deepEqual(plain(futureResult), fromTheFuture);
assert.equal(futureResult.meta.formatVersion, latest + 5); // stamp not downgraded

console.log("Schema version tests passed.");
